"""Checkpoint-first presentation v2 foundation.

Canonical schema, revision identity, registration parsing, content-addressed
asset verification, deterministic validation receipts, the revisioned workspace
that stages, validates, and atomically promotes every mutation, and the
single-checkpoint agent task/patch flow over it, the one sandbox runtime that
executes a checkpoint, the server-issued session cursor, the closed exporters
built on that runtime, and the read-only legacy inventory and migrator.
Checkpoints are the sole navigation and management authority; groups are
optional metadata.
"""

from .agent import (
    AGENT_PATCH_SCHEMA,
    AGENT_RESULT_SCHEMA,
    AGENT_TASK_SCHEMA,
    GRANTABLE_OPERATIONS,
    INHERENT_OPERATIONS,
    OPERATIONS,
    AgentOutcome,
    AgentPatch,
    AgentScope,
    AgentTaskRecord,
    AgentTaskStore,
    checkpoint_state,
    diff_states,
    state_digest,
)
from .contracts import (
    ASSET_MEDIA_TYPES,
    CAPABILITIES,
    CURSOR_SCHEMA,
    DEFAULT_TOTAL_ASSET_BYTES,
    DEFAULT_VALIDATION_POLICY,
    GROUP_KINDS,
    LEGACY_FIELDS,
    MANIFEST_SCHEMA,
    MAX_ASSET_BYTES,
    MAX_ASSETS,
    MAX_TOTAL_ASSET_BYTES_CEILING,
    RECEIPT_SCHEMA,
    REGISTRATION_SCHEMA,
    RUNTIME_VERSION,
    TOTAL_ASSET_BYTES_ENV,
    VALIDATOR_VERSION,
    AssetProvenance,
    AssetRecord,
    Checkpoint,
    Edge,
    Group,
    PresentationManifest,
    StyleRecord,
    Transition,
    ValidationPolicy,
    asset_closure_digest,
    build_edges,
    group_memberships,
    parse_manifest_bytes,
    resolve_validation_policy,
)
from .cursor import CheckpointOrder, DeckCursor
from .errors import Diagnostic, DiagnosticLog, PresentationError, WorkspaceError
from .exporters import (
    DEFERRED_FORMATS,
    EXPORT_SCHEMA,
    Capture,
    ExportResult,
    PlaywrightRasterCapturer,
    RasterCapturer,
    export_index,
    export_offline_html,
    export_raster,
    export_source_archive,
)
from .generation import (
    GeneratedImage,
    GeneratedOutput,
    GenerationPlan,
    GenerationSettings,
    GenerationSpec,
    Style,
    assemble_prompt,
    execute_plan,
    plan_generation,
)
from .jobs import JobRecord, JobStore
from .legacy_stock import LEGACY_STOCK_CHOREOGRAPHY_VERSION, render_stock_choreography
from .migration import (
    CENSUS_SCHEMA,
    INVENTORY_SCHEMA,
    MIGRATION_RECEIPT_SCHEMA,
    LegacyBundle,
    LegacyCandidate,
    LegacyInventory,
    LegacyReadAdapter,
    LegacySlide,
    MigrationPlan,
    MigrationReceipt,
    inventory_presentation,
    is_migrated,
    migration_receipt_path,
    plan_migration,
    promote,
    retirement_census,
    unmigrate,
    verify_migration_receipt,
)
from .receipt import POLICY_DIGEST, ValidationReceipt, compute_revision
from .registration import CheckpointRegistration, parse_registration
from .runtime import (
    DECK_SCHEMA,
    OFFLINE_CAPABILITIES,
    RUNTIME_SHA256,
    DeckPayload,
    build_deck_payload,
    compose_offline_html,
    runtime_manifest,
    runtime_source,
)
from .session import (
    ACTIONS,
    SESSION_SCHEMA,
    SNAPSHOT_SCHEMA,
    SessionService,
    Snapshot,
    reduce_action,
)
from .sources import SourceFile, VerifiedAsset, read_asset, read_source_file
from .store import Promotion, RevisionStore
from .thumbnails import read_thumbnail, render_thumbnail
from .validator import ValidationResult, validate_presentation, verify_receipt
from .workspace import PresentationWorkspace, WorkspaceView, etag_for

__all__ = [
    "ACTIONS",
    "AGENT_PATCH_SCHEMA",
    "AGENT_RESULT_SCHEMA",
    "AGENT_TASK_SCHEMA",
    "ASSET_MEDIA_TYPES",
    "CAPABILITIES",
    "CENSUS_SCHEMA",
    "CURSOR_SCHEMA",
    "DECK_SCHEMA",
    "DEFAULT_TOTAL_ASSET_BYTES",
    "DEFAULT_VALIDATION_POLICY",
    "DEFERRED_FORMATS",
    "EXPORT_SCHEMA",
    "INVENTORY_SCHEMA",
    "MIGRATION_RECEIPT_SCHEMA",
    "OFFLINE_CAPABILITIES",
    "RUNTIME_SHA256",
    "SESSION_SCHEMA",
    "SNAPSHOT_SCHEMA",
    "GRANTABLE_OPERATIONS",
    "GROUP_KINDS",
    "INHERENT_OPERATIONS",
    "LEGACY_FIELDS",
    "LEGACY_STOCK_CHOREOGRAPHY_VERSION",
    "MANIFEST_SCHEMA",
    "MAX_ASSETS",
    "MAX_ASSET_BYTES",
    "MAX_TOTAL_ASSET_BYTES_CEILING",
    "OPERATIONS",
    "POLICY_DIGEST",
    "RECEIPT_SCHEMA",
    "REGISTRATION_SCHEMA",
    "RUNTIME_VERSION",
    "TOTAL_ASSET_BYTES_ENV",
    "VALIDATOR_VERSION",
    "AgentOutcome",
    "AgentPatch",
    "AgentScope",
    "AgentTaskRecord",
    "AgentTaskStore",
    "AssetProvenance",
    "AssetRecord",
    "Capture",
    "Checkpoint",
    "CheckpointOrder",
    "CheckpointRegistration",
    "DeckCursor",
    "DeckPayload",
    "Diagnostic",
    "DiagnosticLog",
    "Edge",
    "ExportResult",
    "GeneratedImage",
    "GeneratedOutput",
    "GenerationPlan",
    "GenerationSettings",
    "GenerationSpec",
    "Group",
    "JobRecord",
    "JobStore",
    "LegacyBundle",
    "LegacyCandidate",
    "LegacyInventory",
    "LegacyReadAdapter",
    "LegacySlide",
    "MigrationPlan",
    "MigrationReceipt",
    "PlaywrightRasterCapturer",
    "PresentationError",
    "PresentationManifest",
    "PresentationWorkspace",
    "Promotion",
    "RasterCapturer",
    "RevisionStore",
    "SessionService",
    "Snapshot",
    "is_migrated",
    "migration_receipt_path",
    "SourceFile",
    "Style",
    "StyleRecord",
    "Transition",
    "ValidationPolicy",
    "ValidationReceipt",
    "ValidationResult",
    "VerifiedAsset",
    "WorkspaceError",
    "WorkspaceView",
    "asset_closure_digest",
    "assemble_prompt",
    "build_deck_payload",
    "build_edges",
    "checkpoint_state",
    "compose_offline_html",
    "compute_revision",
    "diff_states",
    "etag_for",
    "execute_plan",
    "export_index",
    "export_offline_html",
    "export_raster",
    "export_source_archive",
    "group_memberships",
    "inventory_presentation",
    "parse_manifest_bytes",
    "parse_registration",
    "plan_generation",
    "plan_migration",
    "promote",
    "read_asset",
    "read_source_file",
    "read_thumbnail",
    "reduce_action",
    "render_stock_choreography",
    "render_thumbnail",
    "resolve_validation_policy",
    "retirement_census",
    "unmigrate",
    "runtime_manifest",
    "runtime_source",
    "state_digest",
    "validate_presentation",
    "verify_migration_receipt",
    "verify_receipt",
]
